# Конфигурация Dependabot для автоматического обновления зависимостей
# Автоматически проверяет и обновляет зависимости в проекте

version: 2
updates:
  # Обновления для Python зависимостей
  - package-ecosystem: "pip"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "kkobanenko"
    assignees:
      - "kkobanenko"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "ui"
    ignore:
      # Игнорируем major версии для стабильности
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/worker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "kkobanenko"
    assignees:
      - "kkobanenko"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "worker"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/llm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "kkobanenko"
    assignees:
      - "kkobanenko"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "llm"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Обновления для Docker образов
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 3
    reviewers:
      - "kkobanenko"
    assignees:
      - "kkobanenko"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # Игнорируем major версии базовых образов
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]
      - dependency-name: "redis"
        update-types: ["version-update:semver-major"]
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]
      - dependency-name: "clickhouse/clickhouse-server"
        update-types: ["version-update:semver-major"]

  # Обновления для GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 3
    reviewers:
      - "kkobanenko"
    assignees:
      - "kkobanenko"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
