# CI/CD Pipeline для MVP платформы анализа фармацевтических текстов
# Автоматическое тестирование, сборка и деплой всех сервисов

name: CI/CD Pipeline

# Триггеры запуска pipeline
on:
  # Запуск при push в любую ветку
  push:
    branches: [ main, develop, cicd ]
  # Запуск при создании Pull Request
  pull_request:
    branches: [ main, develop ]
  # Запуск при создании тега (для релизов)
  release:
    types: [ published ]
  # Ручной запуск
  workflow_dispatch:

# Переменные окружения для всего pipeline
env:
  # Версии инструментов
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  
  # Названия Docker образов
  UI_IMAGE: pharma-analysis-ui
  WORKER_IMAGE: pharma-analysis-worker
  LLM_IMAGE: pharma-analysis-llm
  
  # Теги для образов
  IMAGE_TAG: ${{ github.sha }}
  LATEST_TAG: latest
  
  # Регистр Docker (можно изменить на свой)
  DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}

# Конфигурация для отмены предыдущих запусков
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Этап 1: Проверка кода и линтинг
  code-quality:
    name: 🔍 Проверка качества кода
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история для анализа изменений
      
      - name: 🐍 Настройка Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: 📦 Установка зависимостей для линтинга
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy bandit safety
      
      - name: 🎨 Проверка форматирования кода (Black)
        run: |
          echo "Проверка форматирования кода с помощью Black..."
          black --check --diff ui/ worker/ llm/ db/ tests/
      
      - name: 📋 Проверка импортов (isort)
        run: |
          echo "Проверка сортировки импортов с помощью isort..."
          isort --check-only --diff ui/ worker/ llm/ db/ tests/
      
      - name: 🔍 Линтинг кода (Flake8)
        run: |
          echo "Линтинг кода с помощью Flake8..."
          flake8 ui/ worker/ llm/ db/ tests/ --max-line-length=100 --ignore=E203,W503
      
      - name: 🔒 Проверка безопасности (Bandit)
        run: |
          echo "Проверка безопасности кода с помощью Bandit..."
          bandit -r ui/ worker/ llm/ db/ -f json -o bandit-report.json || true
          bandit -r ui/ worker/ llm/ db/ -ll
      
      - name: 🛡️ Проверка уязвимостей в зависимостях (Safety)
        run: |
          echo "Проверка уязвимостей в зависимостях..."
          safety check --json --output safety-report.json || true
          safety check
      
      - name: 📊 Загрузка отчетов безопасности
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 30

  # Этап 2: Unit тесты
  unit-tests:
    name: 🧪 Unit тесты
    runs-on: ubuntu-latest
    needs: code-quality
    
    strategy:
      matrix:
        # Тестируем разные компоненты параллельно
        component: [ui, worker, llm, db]
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
      
      - name: 🐍 Настройка Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-mock
          
          # Установка зависимостей для конкретного компонента
          if [ "${{ matrix.component }}" = "ui" ]; then
            pip install -r ui/requirements.txt
          elif [ "${{ matrix.component }}" = "worker" ]; then
            pip install -r worker/requirements.txt
          elif [ "${{ matrix.component }}" = "llm" ]; then
            pip install requests pytest-httpx
          elif [ "${{ matrix.component }}" = "db" ]; then
            pip install psycopg2-binary clickhouse-driver
          fi
          
          # Установка дополнительных зависимостей для покрытия
          pip install pytest-cov
      
      - name: 🧪 Запуск unit тестов
        run: |
          echo "Запуск unit тестов для компонента: ${{ matrix.component }}"
          
          if [ "${{ matrix.component }}" = "ui" ]; then
            python -m pytest ui/test_app.py ui/test_clickhouse.py -v --cov-report=xml --cov-report=html
          elif [ "${{ matrix.component }}" = "worker" ]; then
            python -m pytest worker/test_tasks.py -v --cov=worker --cov-report=xml --cov-report=html
          elif [ "${{ matrix.component }}" = "llm" ]; then
            python -m pytest llm/test_api.py -v --cov=llm --cov-report=xml --cov-report=html
          elif [ "${{ matrix.component }}" = "db" ]; then
            python -m pytest db/test_models.py -v --cov=db --cov-report=xml --cov-report=html
          fi
      
      - name: 📊 Загрузка отчетов покрытия
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-${{ matrix.component }}
          path: |
            coverage.xml
            htmlcov/
          retention-days: 30

  # Этап 3: Integration тесты
  integration-tests:
    name: 🔗 Integration тесты
    runs-on: ubuntu-latest
    needs: unit-tests
    
    services:
      # Запуск Redis для тестов
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Запуск PostgreSQL для тестов
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pharma_analysis_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Запуск ClickHouse для тестов
      clickhouse:
        image: clickhouse/clickhouse-server:23.8-alpine
        ports:
          - 8123:8123
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
      
      - name: 🐍 Настройка Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-mock
          pip install -r ui/requirements.txt
          pip install -r worker/requirements.txt
          pip install requests pytest-httpx
          pip install psycopg2-binary clickhouse-driver
      
      - name: 🗄️ Настройка тестовых баз данных
        run: |
          echo "Настройка тестовых баз данных..."
          
          # Создание схемы PostgreSQL
          PGPASSWORD=postgres psql -h localhost -U postgres -d pharma_analysis_test -f db/migrations/001_init_postgres.sql
          PGPASSWORD=postgres psql -h localhost -U postgres -d pharma_analysis_test -f db/migrations/002_add_text_to_sources.sql
          PGPASSWORD=postgres psql -h localhost -U postgres -d pharma_analysis_test -f db/migrations/003_add_news_table.sql
          
          # Создание схемы ClickHouse
          curl -X POST 'http://localhost:8123/' --data-binary @db/clickhouse/001_init_clickhouse.sql
      
      - name: 🔗 Запуск integration тестов
        run: |
          echo "Запуск integration тестов..."
          python -m pytest tests/test_integration.py -v --tb=short
      
      - name: 🧪 Запуск полного набора тестов
        run: |
          echo "Запуск полного набора тестов..."
          python run_tests.py
      
      - name: 📊 Загрузка результатов тестов
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            test_results.json
            TEST_REPORT.md
          retention-days: 30

  # Этап 4: Security тесты
  security-tests:
    name: 🔒 Security тесты
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
      
      - name: 🐍 Настройка Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          pip install -r ui/requirements.txt
          pip install -r worker/requirements.txt
      
      - name: 🔒 Запуск security тестов
        run: |
          echo "Запуск security тестов..."
          python -m pytest tests/test_security.py -v --tb=short
      
      - name: 🛡️ Сканирование Docker образов на уязвимости
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: 📊 Загрузка результатов security тестов
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-test-results
          path: trivy-results.sarif
          retention-days: 30

  # Этап 5: Сборка Docker образов
  build-images:
    name: 🐳 Сборка Docker образов
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, security-tests]
    
    strategy:
      matrix:
        # Сборка образов для разных компонентов параллельно
        component: [ui, worker, llm]
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
      
      - name: 🐳 Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: 🔐 Логин в GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🏷️ Извлечение метаданных
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ matrix.component }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: 🏗️ Сборка и загрузка Docker образа
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      
      - name: 🏷️ Создание тега для релиза
        if: github.event_name == 'release'
        run: |
          docker tag ${{ env.DOCKER_REGISTRY }}/${{ matrix.component }}:${{ env.LATEST_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ matrix.component }}:${{ github.event.release.tag_name }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ matrix.component }}:${{ github.event.release.tag_name }}

  # Этап 6: Деплой (опционально)
  deploy:
    name: 🚀 Деплой
    runs-on: ubuntu-latest
    needs: build-images
    # Запускается только для main ветки или релизов
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
      
      - name: 🐳 Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: 🔐 Логин в GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🚀 Деплой на сервер
        id: deploy
        run: |
          echo "🚀 Деплой приложения..."
          
          # Здесь можно добавить команды для деплоя на ваш сервер
          # Например, через SSH, Kubernetes, Docker Swarm и т.д.
          
          # Пример для SSH деплоя:
          # echo "Деплой через SSH..."
          # ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
          #   docker pull ${{ env.DOCKER_REGISTRY }}/ui:${{ env.IMAGE_TAG }} &&
          #   docker pull ${{ env.DOCKER_REGISTRY }}/worker:${{ env.IMAGE_TAG }} &&
          #   docker pull ${{ env.DOCKER_REGISTRY }}/llm:${{ env.IMAGE_TAG }} &&
          #   docker-compose down &&
          #   docker-compose up -d
          # "
          
          # Для демонстрации просто выводим информацию
          echo "✅ Деплой завершен успешно!"
          echo "Образы:"
          echo "  - ${{ env.DOCKER_REGISTRY }}/ui:${{ env.IMAGE_TAG }}"
          echo "  - ${{ env.DOCKER_REGISTRY }}/worker:${{ env.IMAGE_TAG }}"
          echo "  - ${{ env.DOCKER_REGISTRY }}/llm:${{ env.IMAGE_TAG }}"
          
          # Устанавливаем URL для environment
          echo "url=https://your-app-domain.com" >> $GITHUB_OUTPUT
      
      - name: 📢 Уведомление о деплое
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Деплой завершен успешно!"
            echo "🌐 Приложение доступно по адресу: ${{ steps.deploy.outputs.url }}"
          else
            echo "❌ Деплой завершился с ошибкой!"
            exit 1
          fi

  # Этап 7: Создание релиза (только для тегов)
  create-release:
    name: 📦 Создание релиза
    runs-on: ubuntu-latest
    needs: [build-images, deploy]
    if: github.event_name == 'release'
    
    steps:
      - name: 📥 Checkout кода
        uses: actions/checkout@v4
      
      - name: 📦 Создание архива релиза
        run: |
          echo "Создание архива релиза..."
          tar -czf pharma-analysis-${{ github.event.release.tag_name }}.tar.gz \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='.pytest_cache' \
            --exclude='htmlcov' \
            --exclude='.coverage' \
            .
      
      - name: 📤 Загрузка архива в релиз
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pharma-analysis-${{ github.event.release.tag_name }}.tar.gz
          asset_name: pharma-analysis-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip

# Уведомления о статусе pipeline
notifications:
  # Можно добавить уведомления в Slack, Discord, Email и т.д.
  # Пример для Slack:
  # - name: Уведомление в Slack
  #   uses: 8398a7/action-slack@v3
  #   if: always()
  #   with:
  #     status: ${{ job.status }}
  #     channel: '#deployments'
  #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}
  #     fields: repo,message,commit,author,action,eventName,ref,workflow
  pass
